### ISSUE TITLE
GoImports not working - possible fix

### ISSUE THREAD

**Issue by Nesh108** [spamwax/goimports-sublime-text-3#2]
Hello,

I am just writing to you because I spent several hours trying to get goimports working with sublime-text-3.
It would always fail for me.

I decided to dig deep down into your code to see if there was something wrong there.

For some reason, -tabs and -tabwidth are not recognized by goimports and that would make the command fail.

I changed this in GoImports.py:

```
       # Save current text into a temp file
        tempPath = save_tmp(self.view)
        cmd = goimports_cmd + " " + tempPath
```

This worked for me and I am extremely happy! :D

**Comment by spamwax** [comment]
Thanks for your feedback. It seems that [goimport](https://github.com/bradfitz/goimports) command is now part of official Go distribution and they have integrated it to the language tools. While your change temporary fixes the problem but it ignores user's settings, so I need to either remove them from the package or figure out how those settings can be passed on to the new goimport command.
I will leave this open till I get some time to investigate this.

**Comment by Nesh108** [comment]
Yeah, the current tabWidth is a bit too high but I couldn't find a way to set it from the args.
